# Generated by Django 3.2.5 on 2022-10-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epaperemail',
            options={'verbose_name': '電子報訂閱信箱', 'verbose_name_plural': '電子報訂閱信箱'},
        ),
    ]
