# Generated by Django 3.2.5 on 2022-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, verbose_name='Order Id')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('zipcode', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('transporting', 'Transporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
            },
        ),
    ]
