# Generated by Django 3.2.5 on 2022-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_relationalproduct'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order_set', through='products.RelationalProduct', to='products.Product'),
        ),
    ]
