# Generated by Django 3.2.5 on 2022-09-30 12:15

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20220926_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='語言代碼')),
                ('language', models.CharField(max_length=50, verbose_name='系統語言')),
                ('sitename', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='系統名稱')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='電話')),
                ('logo', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='logo 圖片')),
                ('favicon', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='favicon 圖片')),
                ('style', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='CSS樣式')),
                ('detail_template', models.CharField(choices=[('Template-1', '版型一'), ('Template-2', '版型二')], default='Template-1', max_length=100, verbose_name='詳細頁面版型')),
                ('facebook', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Facebook 連結')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Instagram 連結')),
                ('twitter', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Twitter 連結')),
                ('home_type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_type1_set', to='products.productcategory', verbose_name='左上商品分類')),
                ('home_type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_type2_set', to='products.productcategory', verbose_name='左下商品分類')),
                ('home_type3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_type3_set', to='products.productcategory', verbose_name='右側商品分類')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
    ]
