# Generated by Django 3.2.5 on 2022-10-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_localesetting_translatesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='繁體中文')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='英文')),
            ],
            options={
                'verbose_name': '欄位多語系',
                'verbose_name_plural': '欄位多語系',
            },
        ),
    ]
